services:
  - type: web
    name: prahari-demo
    env: node
    plan: free
    region: singapore
    rootDir: mplad-app
    buildCommand: "npm install && npx prisma generate && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: PORT
        value: 3000
      - key: NEXTAUTH_URL
        value: https://prahari-demo-lcem.onrender.com
      - key: NEXTAUTH_SECRET
        value: mplads-prahari-portal-2026-secret-key-secure
      - key: NODE_ENV
        value: production
