services:
  - type: web
    name: prahari-demo
    env: node
    plan: free
    region: singapore
    rootDir: mplad-app
    buildCommand: "npm install && npx prisma generate && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: PORT
        value: 3000
